import os
import base64

def embed_files(src, dst, owner, fp):
    for root, dirs, files in os.walk(src):
        home_rel_path = root[7:]
        if len(files):
            install_fp.write("mkdir -p "+dst+"/'"+home_rel_path+"'\n")
        for file in files:
            script_path = dst+"/'"+home_rel_path+"/"+file+"'"
            install_fp.write(f"echo '{home_rel_path+'/'+file}'\n")
            with open(root+"/"+file, "rb") as embed_fp:
                install_fp.write(f'base64 -d > {script_path} <<EOF\n'+(base64.b64encode(embed_fp.read()).decode())+"\nEOF\n")
            install_fp.write('chown '+owner+' '+script_path+"\n")
            install_fp.write('chmod 644 '+script_path+"\n")

with open("install.sh", "w") as install_fp:
    with open("template.sh") as fp:
        for line in fp:
            line = line.strip()
            if line != "# !!FILE_SETUP!!":
                install_fp.write(line+"\n")
            else:
                install_fp.write("# GENERATED BY compile.py\necho '=== populating home directory ==='\n")
                embed_files("./home/", '"$USER_HOME"', "$USER_UID:$USER_GID", install_fp)
                install_fp.write("echo '=== populating root directory ==='\n")
                embed_files("./root/", '', "0:0", install_fp)

