#!/bin/sh

if [ $# -ne 2 ]; then
   echo "Usage: \$0 <partition> <mount_pount>"
   exit 1
fi

ENCODED_ID=$(printf '%s' "$1" | md5sum | cut -d' ' -f1)

cryptsetup luksOpen "$1" "$ENCODED_ID"
if [ $? -ne 0 ]; then
	exit 1
fi

mount /dev/mapper/"$ENCODED_ID" "$2"
