#!/bin/sh

if [ $# -ne 1 ]; then
   echo "Usage: \$0 <partition>"
   exit 1
fi

ENCODED_ID=$(printf '%s' "$1" | md5sum | cut -d' ' -f1)

umount /dev/mapper/"$ENCODED_ID"
sudo cryptsetup luksClose "$ENCODED_ID"
